// Valores constantes del formato (no dependen de la factura).
// Provienen de src/base/Base.xlsx.

export const TITULAR = {
  apellidoPaterno: "TORRES",
  apellidoMaterno: "DÍAZ",
  nombre: "MARÍA ISABEL",
  numeroEmpleado: "77607781",
  // Nombre normalizado (sin acentos, mayúsculas) para comparar con el CFDI.
  nombreCompletoNormalizado: "MARIA ISABEL TORRES DIAZ",
} as const;

export const DEPOSITO = {
  clabe: "012 320 01138129797 2",
  banco: "BBVA",
} as const;

export const EMPRESA =
  "IBM DE MEXICO, COMERCIALIZACION Y SERVICIOS, S. DE R.L. DE C.V.";

export const TITULO_FORMATO = "RELACION DE REEMBOLSOS DE GASTOS CONSULTAS";

export const CONFIDENCIAL = "*IBM Confidential when completed";

export const LUGAR_BASE = "Zapopan Jalisco";

export const AVISO_PRIVACIDAD_PRE = '"RECONOZCO Y ACEPTO QUE ';
export const AVISO_PRIVACIDAD_ASEGURADORA =
  "AON RISK SOLUTIONS AGENTE DE SEGURO Y FINANZAS, S.A de C.V.";
export const AVISO_PRIVACIDAD_POST =
  ', PROCESARÁ LA INFORMACIÓN AQUÍ CONTENIDA O ANEXADA PARA EFECTOS DE MOVIMIENTOS (ALTAS Y BAJAS DE ASEGURADOS), CORRECCIONES, DUPLICADOS, ASÍ COMO LA GESTIÓN, REVISIÓN, EVALUACIÓN Y ACTIVIDADES NECESARIAS PARA HACER EL ANÁLISIS Y DICTAMINACIÓN DE GASTOS MÉDICOS MAYORES PLAN ASEGURADO Y AUTOFINANCIADO, VIDA GRUPO DE CONFORMIDAD CON EL AVISO DE PRIVACIDAD PUBLICADO EN SU PÁGINA DE INTERNET , EL CUAL ME COMPROMETO A ACCEDER A LA BREVEDAD Y MANIFIESTO QUE ES MI INTENCIÓN ADHERIRME AL MISMO ENTENDIÉNDOSE CON LA PRESENTE FIRMA MI CONSENTIMIENTO POR ESCRITO A DICHO AVISO." ';
