// Valores constantes del formato: los que no dependen ni de la factura ni de
// quién lo llena. Provienen de src/base/Base.xlsx.
//
// Los datos del titular (nombre, número de empleado, CLABE, firma, lugar) NO
// viven aquí: son por persona y se capturan en la UI. Ver perfil.ts.

export const EMPRESA =
  "IBM DE MEXICO, COMERCIALIZACION Y SERVICIOS, S. DE R.L. DE C.V.";

export const TITULO_FORMATO = "RELACION DE REEMBOLSOS DE GASTOS CONSULTAS";

export const CONFIDENCIAL = "*IBM Confidential when completed";

export const AVISO_PRIVACIDAD_PRE = '"RECONOZCO Y ACEPTO QUE ';
export const AVISO_PRIVACIDAD_ASEGURADORA =
  "AON RISK SOLUTIONS AGENTE DE SEGURO Y FINANZAS, S.A de C.V.";
export const AVISO_PRIVACIDAD_POST =
  ', PROCESARÁ LA INFORMACIÓN AQUÍ CONTENIDA O ANEXADA PARA EFECTOS DE MOVIMIENTOS (ALTAS Y BAJAS DE ASEGURADOS), CORRECCIONES, DUPLICADOS, ASÍ COMO LA GESTIÓN, REVISIÓN, EVALUACIÓN Y ACTIVIDADES NECESARIAS PARA HACER EL ANÁLISIS Y DICTAMINACIÓN DE GASTOS MÉDICOS MAYORES PLAN ASEGURADO Y AUTOFINANCIADO, VIDA GRUPO DE CONFORMIDAD CON EL AVISO DE PRIVACIDAD PUBLICADO EN SU PÁGINA DE INTERNET , EL CUAL ME COMPROMETO A ACCEDER A LA BREVEDAD Y MANIFIESTO QUE ES MI INTENCIÓN ADHERIRME AL MISMO ENTENDIÉNDOSE CON LA PRESENTE FIRMA MI CONSENTIMIENTO POR ESCRITO A DICHO AVISO." ';
